### ISSUE TITLE
Whitepaper spelt wrong and github link placed wrong 

### ISSUE THREAD

**Issue by Shreyas-ITB** [kryptokrona/xkr-website#1]
[Typo](https://github.com/kryptokrona/xkr-website/blob/main/src/lib/components/Footer.svelte) fix it Swepool the whitepaper is completely wrong and the github button redirects to github.com not to this repository tho

**Comment by Swepool** [comment]
Now fixed, thanks for creating an issue

https://github.com/kryptokrona/xkr-website/pull/4
https://github.com/kryptokrona/xkr-website/pull/2
