### ISSUE TITLE
Whitepaper links is in.se and not .org

### ISSUE THREAD

**Issue by DanielBoye** [kryptokrona/xkr-website#12]
The whitepapers are currently linked to the kryptokrona.se website. I'm working on a fix so the pdfs will be on the .org

**Comment by Swepool** [comment]
I think we can upload the wp to xkr-website and get it in public folder. Then we can link to it :)

**Comment by Swepool** [comment]
Either a config in vite or maybe just upload it to static folder and link to it.

**Comment by DanielBoye** [comment]
Was working on a fix for it but needed to go to the store, I'm on it now

**Comment by Swepool** [comment]
Nice 😄

**Comment by DanielBoye** [comment]
Temporarily fix with making the .pdfs on the /static and just linking the href="" to the github folder
