### ISSUE TITLE
Guides Button under XKR does not work

### ISSUE THREAD

**Issue by DanielBoye** [kryptokrona/xkr-website#17]
It points to the directory of https://docs.kryptokrona.org. Is this a future website for hosting all of the guides? 

I was thinking of making a guide for how to buy XKR, and I wanted to add it to the docs. Should I just add a blog post, or wait till we get the domain up and running?

**Comment by Swepool** [comment]
Write your guide in markdown and send it on git :)

**Comment by DanielBoye** [comment]
> Write your guide in markdown and send it on discord or upload it to docs :)

Pushed it to the docs now ;)
