### ISSUE TITLE
Making a Q&A for mining questions

### ISSUE THREAD

**Issue by DanielBoye** [kryptokrona/xkr-website#28]

**Comment by mjovanc** [comment]
@Swepool @f-r00t Should perhaps be on the docs.kryptokrona.org?

**Comment by f-r00t** [comment]
Agreed.

**Comment by DanielBoye** [comment]
Will look into it with making question and answers. Don't know how much and long it will take me but I will see.

**Comment by f-r00t** [comment]
Nice, keep us posted!
